
[{
     "id": 1,
        "marca": "Fiere",
        "modelo": "FM18SI29AM11",
        "rodado": 16,
        "año": 2019,
        "color": "celeste",
        "paso":13,
        "tipo": "montañera",
        "vendida": "no"
},
{
     "id" : 2,
        "marca": "shifter", 
        "modelo":"FM18F29AM210",
        "rodado": 26,
        "año": 2020,
        "color": "negro",
        "paso": 15,
        "tipo": "paseo",
        "vendida":"true",
},
{
    "id" : 3,
        "marca": "olmo",
        "modelo": "Regal",
        "rodado": 28,
        "año": 2021,
        "color": "gris",
        "paso": 16,
        "tipo": "Retro",
        "precio" : 50.000,
        "vendida": "si",
},
{
     "id" : 4,
        "marca": "zero" ,
        "modelo": "TERK" ,
        "rodado": 29,
        "año" : 2022,
        "color": "violeta",
        "paso": 10 ,
        "tipo": "montain bike",
        "presio": 54.569,
        "vendida": "false",
}]
